version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      production-deps:
        dependency-type: "production"
      development-deps:
        dependency-type: "development"
