repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args:
          [
            "--config=backend/pyproject.toml",
          ]
        files: ^backend/.*\.py$
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^backend/.*\.py$
  - repo: local
    hooks:
      - id: pylint
        name: PyLint
        entry: pylint
        args:
          [
            "--rcfile=backend/.pylintrc",
          ]
        language: system
        files: ^backend/.*\.py$
        require_serial: true
      - id: mypy
        name: MyPy
        entry: mypy
        args:
          [
            "--config-file=backend/mypy.ini",
          ]
        language: system
        files: ^backend/.*\.py$
        require_serial: true
