version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: development
    restart: always
    env_file: env/.env.dev
    ports:
      - "${API_PORT}:8000"
    networks:
      - backend
    volumes:
      - ../backend/taskmanager:/app/taskmanager

networks:
  backend:
    driver: bridge
