
services:
  api:
    container_name: api
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: production
    restart: always
    ports:
      - "${API_PORT}:8000"
    networks:
      - backend
    hostname: api

networks:
  backend:
    driver: bridge
