name: Lint Check

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
          cache-dependency-path: backend/poetry.lock

      - name: Install dependencies
        working-directory: backend
        run: poetry install --with dev,lint

      - name: Lint with pre-commit
        working-directory: backend
        run: poetry run pre-commit run --all-files
